import { StyleSheet, Dimensions, Platform } from 'react-native';
import { colors } from '../../utils';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    backgroundColor: colors.primary,
    paddingTop: Platform.OS === 'ios' ? 50 : 16,
  },
  backButton: {
    marginRight: 16,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.white,
  },
  content: {
    flex: 1,
  },
  bannerContainer: {
    height: 200,
    width: '100%',
    position: 'relative',
  },
  bannerImage: {
    width: '100%',
    height: '100%',
  },
  bannerGradient: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 100,
    backgroundColor: 'rgba(0,0,0,0.3)',
  },
  bannerPlaceholder: {
    width: '100%',
    height: '100%',
    backgroundColor: colors.gray,
    justifyContent: 'center',
    alignItems: 'center',
  },
  bannerPlaceholderText: {
    color: colors.text,
    fontSize: 16,
  },
  changeImageButton: {
    position: 'absolute',
    bottom: 16,
    right: 16,
    backgroundColor: colors.primary,
    padding: 8,
    borderRadius: 20,
  },
  bannerTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: colors.white,
  },
  sectionContainer: {
    padding: 16,
    backgroundColor: colors.white,
    marginBottom: 8,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.text,
    marginBottom: 16,
  },
  formGroup: {
    marginBottom: 16,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  label: {
    fontSize: 14,
    color: colors.text,
    marginBottom: 8,
  },
  input: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    color: colors.text,
    backgroundColor: colors.white,
  },
  pickerContainer: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    backgroundColor: colors.white,
  },
  picker: {
    height: 50,
  },
  dateInput: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    padding: 12,
    backgroundColor: colors.white,
  },
  updateButton: {
    backgroundColor: colors.primary,
    padding: 16,
    borderRadius: 8,
    alignItems: 'center',
    margin: 16,
  },
  updateButtonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: 'bold',
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.lightGray,
    borderRadius: 8,
    paddingHorizontal: 12,
  },
  inputIcon: {
    marginRight: 8,
  },
  locationInputContainer: {
    marginBottom: 10,
  },
  locationInput: {
    flex: 1,
    fontSize: 16,
    color: colors.text,
    paddingVertical: 12,
    paddingHorizontal: 8,
  },
  locationAddress: {
    fontSize: 14,
    color: colors.textSecondary,
    marginTop: 4,
  },
  privacyContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  privacyButton: {
    flex: 1,
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
    marginHorizontal: 5,
    alignItems: 'center',
    backgroundColor: colors.white,
  },
  privacyButtonActive: {
    backgroundColor: colors.Zypsii_color,
    borderColor: colors.Zypsii_color,
  },
  privacyButtonText: {
    fontSize: 16,
    color: colors.text,
  },
  privacyButtonTextActive: {
    color: colors.white,
    fontWeight: '500',
  },
  dayCard: {
    backgroundColor: colors.white,
    borderRadius: 12,
    padding: 15,
    marginBottom: 15,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  dayHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
    paddingHorizontal: 10,
  },
  dayTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
  },
  dayDate: {
    fontSize: 14,
    color: '#666',
    marginLeft: 10,
  },
  removeDayButton: {
    padding: 5,
  },
  mapButton: {
    backgroundColor: colors.Zypsii_color,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 12,
    borderRadius: 8,
    marginBottom: 10,
  },
  mapButtonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: 'bold',
    marginLeft: 8,
  },
  mapContainer: {
    height: 200,
    marginTop: 10,
    borderRadius: 10,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.grayLinesColor,
  },
  map: {
    width: '100%',
    height: '100%',
  },
  timeContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 10,
  },
  timeButton: {
    flex: 1,
    backgroundColor: colors.background,
    padding: 12,
    borderRadius: 8,
    marginHorizontal: 5,
    alignItems: 'center',
  },
  timeText: {
    fontSize: 16,
    color: colors.fontMainColor,
  },
  locationList: {
    marginTop: 10,
    padding: 10,
    backgroundColor: colors.lightGray,
    borderRadius: 8,
  },
  locationItem: {
    marginBottom: 8,
    padding: 8,
    backgroundColor: colors.white,
    borderRadius: 6,
  },
  locationHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 5,
  },
  locationName: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.text,
  },
  locationDistance: {
    fontSize: 12,
    color: colors.primary,
    marginTop: 4,
  },
  miniMapContainer: {
    height: 100,
    borderRadius: 8,
    overflow: 'hidden',
    marginTop: 5,
  },
  miniMap: {
    flex: 1,
  },
  addLocationButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f0f0f0',
    padding: 10,
    borderRadius: 8,
    marginTop: 10,
  },
  addLocationButtonText: {
    color: '#A60F93',
    marginLeft: 5,
    fontSize: 14,
    fontWeight: '500',
  },
  addDayButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 12,
    borderRadius: 8,
    marginTop: 10,
    backgroundColor: colors.background,
  },
  addDayButtonText: {
    color: colors.Zypsii_color,
    fontSize: 16,
    fontWeight: 'bold',
    marginLeft: 8,
  },
  datePickerButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 12,
    borderWidth: 1,
    borderColor: colors.grayLinesColor,
    borderRadius: 8,
    backgroundColor: colors.white,
  },
  timePickerButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 12,
    borderWidth: 1,
    borderColor: colors.grayLinesColor,
    borderRadius: 8,
    backgroundColor: colors.white,
    marginTop: 10,
  },
  dateText: {
    fontSize: 16,
    color: colors.fontMainColor,
  },
  timeText: {
    fontSize: 16,
    color: colors.fontMainColor,
  },
  datePlaceholder: {
    color: colors.graycolor,
  },
  timePlaceholder: {
    color: colors.graycolor,
  },
  locationText: {
    fontSize: 16,
    color: colors.text,
    paddingVertical: 12,
  },
  updateDayButton: {
    backgroundColor: colors.primary,
    padding: 12,
    borderRadius: 8,
    marginTop: 10,
    alignItems: 'center',
  },
  updateDayButtonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: '600',
  },
}); 