import { StyleSheet, Dimensions, Platform } from 'react-native';
import { colors } from '../../utils/colors';

const { width } = Dimensions.get('window');

export default StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: '#F8F9FA',
  },
  headerGradient: {
    paddingTop: Platform.OS === 'ios' ? 50 : 40,
    paddingBottom: 40,
    paddingHorizontal: 20,
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    marginBottom: 20,
    shadowColor: '#A60F93',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 8,
  },
  headerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  backButton: {
    marginRight: 15,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: 'white',
  },
  container: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 30,
  },
  tripContainer: {
    padding: 20,
    marginTop: -20,
  },
  bannerContainer: {
    height: 200,
    borderRadius: 20,
    overflow: 'hidden',
    marginBottom: 25,
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 6,
    },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
    borderWidth: 1,
    borderColor: 'rgba(166, 15, 147, 0.1)',
  },
  bannerImage: {
    width: '100%',
    height: '100%',
  },
  bannerPlaceholder: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'linear-gradient(135deg, #F8F9FA 0%, #E9ECEF 100%)',
    borderWidth: 2,
    borderColor: 'rgba(166, 15, 147, 0.2)',
    borderStyle: 'dashed',
  },
  bannerPlaceholderText: {
    marginTop: 10,
    color: '#666',
    fontSize: 16,
    fontWeight: '600',
  },
  formGroupRow: {
    marginBottom: 25,
  },
  labelRow: {
    fontSize: 18,
    fontWeight: '700',
    color: '#2C3E50',
    marginBottom: 12,
    letterSpacing: 0.5,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 16,
    paddingHorizontal: 18,
    paddingVertical: 16,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 3,
    borderWidth: 1,
    borderColor: 'rgba(166, 15, 147, 0.1)',
  },
  inputIcon: {
    marginRight: 14,
    color: '#A60F93',
  },
  underlineInput: {
    flex: 1,
    fontSize: 16,
    color: '#2C3E50',
    fontWeight: '500',
  },
  sectionContainer: {
    marginBottom: 30,
  },
  sectionTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: '#2C3E50',
    marginBottom: 18,
    letterSpacing: 1,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 15,
  },
  formGroup: {
    flex: 1,
    padding: 4,
  },
  input: {
    flex: 1,
    fontSize: 16,
    color: '#2C3E50',
    fontWeight: '500',
  },
  datePickerButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#fff',
    borderRadius: 16,
    paddingHorizontal: 18,
    paddingVertical: 16,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 3,
    borderWidth: 1,
    borderColor: 'rgba(166, 15, 147, 0.1)',
  },
  dateText: {
    fontSize: 16,
    color: '#2C3E50',
    fontWeight: '500',
  },
  datePlaceholder: {
    color: '#95A5A6',
    fontWeight: '400',
  },
  dayCard: {
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 24,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 6,
    },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 6,
    borderWidth: 1,
    borderColor: 'rgba(166, 15, 147, 0.08)',
  },
  dayHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 18,
  },
  dayTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#2C3E50',
    letterSpacing: 0.5,
  },
  removeDayButton: {
    padding: 10,
    backgroundColor: '#FFF5F5',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(229, 57, 53, 0.2)',
  },
  dayInput: {
    borderWidth: 2,
    borderColor: colors.border,
    borderRadius: 12,
    padding: 16,
    marginBottom: 15,
    minHeight: 120,
    textAlignVertical: 'top',
    fontSize: 16,
    fontWeight: '500',
    backgroundColor: '#FAFBFC',
  },
  disabledInput: {
    backgroundColor: colors.lightGray,
    opacity: 0.7,
    borderColor: '#E9ECEF',
  },
  mapButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#A60F93',
    padding: 18,
    borderRadius: 16,
    marginBottom: 18,
    shadowColor: '#A60F93',
    shadowOffset: {
      width: 0,
      height: 6,
    },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 8,
  },
  mapButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
    marginLeft: 10,
    letterSpacing: 0.5,
  },
  map: {
    height: 200,
    borderRadius: 16,
    marginBottom: 18,
    borderWidth: 2,
    borderColor: 'rgba(166, 15, 147, 0.1)',
  },
  timeContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  timeButton: {
    flex: 1,
    backgroundColor: '#F8F9FA',
    padding: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(166, 15, 147, 0.2)',
    alignItems: 'center',
  },
  timeText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#2C3E50',
  },
  addDayButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 18,
    backgroundColor: '#F8F9FA',
    borderRadius: 16,
    marginTop: 15,
    borderWidth: 2,
    borderColor: '#A60F93',
    borderStyle: 'dashed',
    shadowColor: '#A60F93',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 3,
  },
  addDayButtonText: {
    color: '#A60F93',
    fontSize: 16,
    fontWeight: '700',
    marginLeft: 10,
    letterSpacing: 0.5,
  },
  submitButton: {
    marginTop: 35,
    borderRadius: 16,
    overflow: 'hidden',
    shadowColor: '#A60F93',
    shadowOffset: {
      width: 0,
      height: 6,
    },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 8,
  },
  submitButtonGradient: {
    padding: 20,
    alignItems: 'center',
  },
  submitButtonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  visibilityButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 18,
    marginHorizontal: 5,
    borderWidth: 2,
    borderColor: 'rgba(166, 15, 147, 0.1)',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 3,
  },
  visibilityButtonActive: {
    backgroundColor: '#A60F93',
    borderColor: '#A60F93',
    shadowColor: '#A60F93',
    shadowOpacity: 0.3,
  },
  visibilityButtonText: {
    fontSize: 16,
    color: '#666',
    marginLeft: 10,
    fontWeight: '600',
  },
  visibilityButtonTextActive: {
    color: '#fff',
    fontWeight: '700',
  },
  locationMap: {
    height: 150,
    width: '100%',
    marginTop: 12,
    borderRadius: 12,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: 'rgba(166, 15, 147, 0.1)',
  },
  // Validation error styles
  errorContainer: {
    backgroundColor: '#FFF5F5',
    borderWidth: 1,
    borderColor: '#FECACA',
    borderRadius: 8,
    padding: 8,
    marginTop: 4,
  },
  errorText: {
    color: '#DC2626',
    fontSize: 12,
    fontWeight: '500',
  },
  // Success state styles
  successContainer: {
    backgroundColor: '#F0FDF4',
    borderWidth: 1,
    borderColor: '#BBF7D0',
    borderRadius: 8,
    padding: 8,
    marginTop: 4,
  },
  successText: {
    color: '#16A34A',
    fontSize: 12,
    fontWeight: '500',
  },
});
